export const HTTP_STATUS = {
  BAD_REQUEST: 400,
  AUTHORIZATION_ERROR: 401,
  FORBIDDEN: 403,
  NOT_FOUND: 404,
  VALIDATION_ERROR: 422,
  INTERNAL_ERROR: 500,
};

export const BLOCKNUMBER_LIMIT_SCAN_EVENT = 1000;

export const DATE_TIME_STRING_FORMAT = 'YYYY-MM-DD HH:mm:ss';
